/* Auto-generated by tools/gen-overrides.py — ICE / ECS / Pedestal / AVNCS XPDR */
function cycleFwdDeice(){ sendP('SSP_ICE_FWD_WING_DEICE_CYCLE'); }
function cycleMainDeice(){ sendP('SSP_ICE_MAIN_WING_DEICE_CYCLE'); }

/* ECS helpers (from ecs.html) */
function clamp(n,min,max){ return Math.max(min, Math.min(max, n)); }
    function adjLVar(name,type,delta,min,max){
      var cur=getLVar(name,type); if(cur===undefined||cur===null) cur=min||0;
      var next=Number(cur)+delta;
      if(min!==undefined) next=Math.max(min,next);
      if(max!==undefined) next=Math.min(max,next);
      setLVar(name,type,next);
      return next;
    }
    function cycleBleed(){ sendP('SSP_ECS_BLEED_MODE_CYCLE'); }
    function bleedDec(){ sendP('SSP_ECS_BLEED_MODE_DEC'); }
    function bleedInc(){ sendP('SSP_ECS_BLEED_MODE_INC'); }
    function cycleBlower(){ pingPong('var_CockpitBlowerKnob','Number',0,10,1); pingPong('var_CabinBlowerKnob','Number',0,10,1); }
    function blowerDec(){
      adjLVar('var_CockpitBlowerKnob','Number',-1,0,10);
      adjLVar('var_CabinBlowerKnob','Number',-1,0,10);
    }
    function blowerInc(){
      adjLVar('var_CockpitBlowerKnob','Number', 1,0,10);
      adjLVar('var_CabinBlowerKnob','Number', 1,0,10);
    }
    function cycleTempMode(){ sendP('SSP_ECS_TEMP_MODE_CYCLE'); }
    function toggleCockCabMode(){ sendP('SSP_ECS_TEMP_SCOPE_CKPT_CAB_TOGGLE'); }
    function ckptTempDec(){ sendP('SSP_ECS_TEMP_CKPT_DEC'); }
    function ckptTempInc(){ sendP('SSP_ECS_TEMP_CKPT_INC'); }
    function cabTempDec(){ sendP('SSP_ECS_TEMP_CAB_DEC'); }
    function cabTempInc(){ sendP('SSP_ECS_TEMP_CAB_INC'); }
    function combTempDec(){ sendP('SSP_ECS_TEMP_MAN_DEC'); }
    function combTempInc(){ sendP('SSP_ECS_TEMP_MAN_INC'); }
    function cabinAltDec(){ sendP('SSP_ECS_CAB_ALT_DEC'); }
    function cabinAltInc(){ sendP('SSP_ECS_CAB_ALT_INC'); }
    function cabinAltDecFast(){ sendP('SSP_ECS_CAB_ALT_FAST_DEC'); }
    function cabinAltIncFast(){ sendP('SSP_ECS_CAB_ALT_FAST_INC'); }
    function cabinRateDec(){ sendP('SSP_ECS_CAB_RATE_DEC'); }
    function cabinRateInc(){ sendP('SSP_ECS_CAB_RATE_INC'); }

    function fmtInt(v){ return (v===undefined||v===null) ? '\u2014' : String(Math.round(Number(v))); }
    function fmt1(v){
      if(v===undefined||v===null) return '\u2014';
      var n=Number(v);
      return isNaN(n) ? '\u2014' : n.toFixed(1);
    }
    function numOrU(v){
      var n=Number(v);
      return isFinite(n) ? n : undefined;
    }
    function fToC(f){ return (Number(f)-32)*(5/9); }
    function fmtTempFromF(fVal, isC){
      var n=numOrU(fVal);
      if(n===undefined) return '\u2014';
      return String(Math.round(isC ? fToC(n) : n));
    }
    function setTempLabels(isC){
      var unit=isC?'C':'F';
      var ck=document.getElementById('ckptTmpLbl'); if(ck) ck.innerHTML='CKPT SET &deg;'+unit;
      var cb=document.getElementById('cabTmpLbl'); if(cb) cb.innerHTML='CAB TMP &deg;'+unit;
      var mn=document.getElementById('manTmpLbl'); if(mn) mn.innerHTML='MAN SET &deg;'+unit;
      var sp=document.getElementById('setpointLbl'); if(sp) sp.innerHTML='SETPOINT &deg;'+unit;
      var cv=document.getElementById('cabVentLbl'); if(cv) cv.innerHTML='CAB VENT &deg;'+unit;
    }
    function bleedStateLabel(v){
      var n=Number(v);
      if(n===1) return 'OFF';
      if(n===0) return 'R';
      if(n===2) return 'L';
      if(n===3) return 'BOTH';
      if(n===4) return 'R AUTO';
      if(n===5) return 'BOTH AUTO';
      return '\u2014';
    }

    function dimBtn(id, dimmed){
      var el=document.getElementById(id);
      if(!el) return;
      el.style.opacity = dimmed ? '0.35' : '1';
      el.style.pointerEvents = dimmed ? 'none' : '';
    }

function pollEcs(){ try {
setValDisplay('bleedVal', getLVar('var_BleedAirValveSwitch','Number'));
      setValDisplay('blowerCkptVal', getLVar('var_CockpitBlowerKnob','Number'));
      setValDisplay('blowerCabVal', getLVar('var_CabinBlowerKnob','Number'));
      var bState=Number(getLVar('var_BleedAirValveSwitch','Number'));
      var blIds=['blR','blOff','blL','blBoth','blRA','blBA'];
      for(var i=0;i<blIds.length;i++){
        var el=document.getElementById(blIds[i]);
        if(el) el.classList.toggle('on', i===bState);
      }

      var tm=Number(getLVar('var_EnvironmentalModeKnob','Number'));
      setLamps(['tmManLamp','tmOffLamp','tmAutoLamp'], tm==0?0:tm==2?2:1);
      setToggleVisual('cockCabBtn','cockCabInd', getLVar('AAOCockCabTmp','Number')==1);
      var tempInC=(getLVar('BKSQ_CABINTEMPDISPLAYFORCECELSIUS','Bool')==1);
      setToggleVisual('tempUnitBtn','tempUnitInd', tempInC);
      setValDisplay('tempUnitTxt', tempInC ? 'C' : 'F');
      setTempLabels(tempInC);

      var isMan=(tm===0), isAuto=(tm===2);
      var ckptKnob=numOrU(getLVar('var_CockpitTemperatureKnob','Number'));
      var cabTempF=numOrU(getLVar('var_CabinTemperature','Number'));
      if(cabTempF===undefined) cabTempF=numOrU(getLVar('VAR_CABINTEMPERATURE','Number'));
      if(cabTempF===undefined) cabTempF=numOrU(getAVar('AMBIENT TEMPERATURE, fahrenheit'));
      var manSetF=numOrU(getLVar('var_cabinTempManualSet','Number'));
      var autoSetF=numOrU(getLVar('var_CabinTempSetPoint','Number'));
      if(autoSetF===undefined){
        var cabKnob=numOrU(getLVar('var_CabinTemperatureKnob','Number'));
        if(ckptKnob!==undefined&&cabKnob!==undefined) autoSetF=((ckptKnob+cabKnob)/2)+60;
      }
      var cabVentF=numOrU(getLVar('var_CabinVentTemperature','Number'));

      setValDisplay('ckptTmpVal', fmtTempFromF(ckptKnob!==undefined ? (ckptKnob+60) : undefined, tempInC));
      setValDisplay('cabTmpVal', fmtTempFromF(cabTempF, tempInC));
      setValDisplay('manTmpVal', fmtTempFromF(manSetF, tempInC));
      dimBtn('ckptDecBtn', !isAuto); dimBtn('ckptIncBtn', !isAuto);
      dimBtn('cabDecBtn', !isAuto); dimBtn('cabIncBtn', !isAuto);
      dimBtn('manDecBtn', !isMan); dimBtn('manIncBtn', !isMan);

      var setptF = autoSetF;
      if(isMan&&manSetF!==undefined) setptF=manSetF;
      setValDisplay('setpointVal', tm===1 ? 'OFF' : fmtTempFromF(setptF, tempInC));
      setValDisplay('cabVentVal', fmtTempFromF(cabVentF, tempInC));

      setValDisplay('pressAltVal', fmtInt(getLVar('var_pressurizationGoal','Feet')));
      setValDisplay('cabAltVal', fmtInt(getLVar('var_cabinPressurizationAltitude','Feet')));
      var cd=getLVar('var_cabinPressureDifferential','Number');
      setValDisplay('cabDiffVal', cd!==undefined?Number(cd).toFixed(1):undefined);
      var cr=getLVar('var_cabinClimbRate','Number');
      setValDisplay('cabRateVal', fmtInt(cr));
      var pneuL=getLVar('var_BleedAirPressure_L','psi');
      var pneuR=getLVar('var_BleedAirPressure_R','psi');
      if(pneuL===undefined||pneuL===null) pneuL=getAVar('PNEUMATIC PRESSURE:1, psi');
      if(pneuR===undefined||pneuR===null) pneuR=getAVar('PNEUMATIC PRESSURE:2, psi');
      setValDisplay('pneuLVal', fmt1(pneuL));
      setValDisplay('pneuRVal', fmt1(pneuR));

      var ss=getLVar('var_AlternateStaticSwitch','Bool')==1;
      setLamps(['ssIsoLamp','ssNormLamp'], ss?0:1);
      setToggleVisual('oxySysBtn','oxySysInd', getLVar('XMLVAR_Cabin_Air_4_Position','Number')==100);
      setToggleVisual('oxyPltBtn','oxyPltInd', getLVar('var_pilotOxygen','Bool')==1);
      var cpOxy=(getLVar('var_copilotOxygen','Bool')==1) || (getLVar('var_coPilotOxygen','Bool')==1);
      setToggleVisual('oxyCpBtn','oxyCpInd', cpOxy);
      setToggleVisual('paxOxyBtn','paxOxyInd', getLVar('XMLVAR_Cabin_Air_5_Position','Number')==100);
      var oxyP=getAVar('OXYGEN TANK PRESSURE:1, psi');
      if(oxyP===undefined||oxyP===null) oxyP=getAVar('OXYGEN TANK PRESSURE, psi');
      if(oxyP===undefined||oxyP===null) oxyP=getLVar('var_OxygenPressure','Number');
      setValDisplay('oxyPressVal', fmtInt(oxyP));
} catch(e){} }

/* Pedestal (from pedestal.html) */
    var VOLT_MODES=['L GEN','CTR BUS','R GEN','TRIP FED','EXT PWR','BATT'];
    var VOLT_SOURCE_LVARS=[
      'var_Multimeter_LeftBusVolts',
      'var_Multimeter_CenterBusVolts',
      'var_Multimeter_RightBusVolts',
      'var_Multimeter_TripleFedBusVolts',
      'var_Multimeter_ExternalPowerVolts',
      'var_Multimeter_BatteryVolts'
    ];

    function cycleBusTie(){ sendP('SSP_PED_ELEC_GEN_TIES_CYCLE'); }
    var _genLPhase=0, _genRPhase=0;
    function cycleGenL(){ sendP('SSP_PED_ELEC_GEN_L_CYCLE'); }
    function cycleGenR(){ sendP('SSP_PED_ELEC_GEN_R_CYCLE'); }
    function cycleAutoFeather(){ sendP('SSP_PED_PROP_AUTOFEATHER_CYCLE'); }
    function cycleStarterL(){ sendP('SSP_PED_ENG_STARTER_L_CYCLE'); }
    function cycleStarterR(){ sendP('SSP_PED_ENG_STARTER_R_CYCLE'); }
    function cyclePropGov(){ sendP('SSP_PED_PROP_GOV_CYCLE'); }
    function holdScript(holdLabel){
      if(!holdLabel) return;
      sendP(holdLabel);
    }
    function pulseStdbyPwr(){
      holdScript('SSP_PED_ELEC_STBY_IND_PWR_HOLD');
    }
    function cyclePitchTrim(){ sendP('SSP_PED_TRIM_PITCH_MODE_CYCLE'); }
    function togglePrkBrk(){
      sendP('SSP_PED_BRAKE_PARK_TOGGLE');
    }
    function cycleFuelXfer(){ sendP('SSP_PED_FUEL_TRANSFER_CYCLE'); }
    function aftQtyPush(side){
      var s=(side==='R')?'R':'L';
      var hLabel = (s==='R') ? 'SSP_PED_FUEL_AFT_QTY_R_HOLD' : 'SSP_PED_FUEL_AFT_QTY_L_HOLD';
      holdScript(hLabel);
    }
    function voltSelDec(){ sendP('SSP_PED_ELEC_VOLT_SEL_DEC'); }
    function voltSelInc(){ sendP('SSP_PED_ELEC_VOLT_SEL_INC'); }

    function fmtNum(v, dec){
      if(v===undefined||v===null) return '\u2014';
      var n=Number(v);
      return isNaN(n) ? '\u2014' : n.toFixed(dec);
    }
    function numOrU(v){
      var n=Number(v);
      return isFinite(n) ? n : undefined;
    }
    function clamp(n,min,max){ return Math.max(min, Math.min(max, n)); }
    /* Gen load: interior GenMaxAmps=300, var_CorrectedGeneratorAmps from GENALT amps times busV over 28V. */
    var GEN_LOAD_FULL_SCALE_AMPS = 300;
    function toLoadPct(amps){
      if(amps===undefined||amps===null) return undefined;
      var n=Number(amps);
      if(isNaN(n)) return undefined;
      return clamp((Math.abs(n)/GEN_LOAD_FULL_SCALE_AMPS)*100, 0, 999);
    }
    function normalizePct(v){
      if(v===undefined||v===null) return undefined;
      var n=Number(v);
      if(isNaN(n)) return undefined;
      // Some vars return 0..1, others 0..100.
      if(n<=1.2) n=n*100;
      return clamp(n,0,999);
    }
    function readCorrectedGenAmps(idx){
      var name=(idx===1)?'var_CorrectedGeneratorAmps_L':'var_CorrectedGeneratorAmps_R';
      return numOrU(getLVar(name,'Number'));
    }
    /* Integer % like cockpit digital readout (nearest whole). */
    function fmtLoadPctInt(pct){
      if(pct===undefined||pct===null||isNaN(Number(pct))) return '\u2014';
      return String(Math.round(clamp(Number(pct),0,999)));
    }
    var _lastGenLoadPct={1:0,2:0};
    function isGenSideOnline(idx){
      var lName=(idx===1)?'var_GeneratorOnline_L':'var_GeneratorOnline_R';
      var o=numOrU(getLVar(lName,'Number'));
      if(o===1) return true;
      if(o===0) return false;
      /* Match interior macro: alternator on + prop RPM > 200 */
      var altOn=getAVar('GENERAL ENG MASTER ALTERNATOR:'+idx+', Bool')==1;
      var rpm=numOrU(getAVar('PROP RPM:'+idx+', rpm'));
      return altOn && rpm!==undefined && rpm>200;
    }
    function getGenLoadPct(side){
      var idx=(side===2)?2:1;
      var on=isGenSideOnline(idx);
      if(!on){
        _lastGenLoadPct[idx]=0;
        return 0;
      }

      /* 1) Aircraft-defined load (interior GenMaxAmps 300 + var_CorrectedGeneratorAmps_*) */
      var corrected=readCorrectedGenAmps(idx);
      var pct=toLoadPct(corrected);
      if(pct!==undefined){
        _lastGenLoadPct[idx]=pct;
        return pct;
      }

      /* 2) Recompute same formula as interior if L: is missing this frame */
      var amps=numOrU(getAVar('ELECTRICAL GENALT BUS AMPS:'+idx+', amps'));
      if(amps!==undefined){
        var volts=numOrU(getAVar('ELECTRICAL GENALT BUS VOLTAGE:'+idx+', volts'));
        if(volts!==undefined) amps = amps * (volts/28);
        pct=toLoadPct(amps);
        if(pct!==undefined){
          _lastGenLoadPct[idx]=pct;
          return pct;
        }
      }

      /* 3) Native sim % — can diverge ~1 from pedestal multimeter */
      pct=normalizePct(getAVar('ELECTRICAL GENALT LOAD:'+idx+', percent'));
      if(pct!==undefined){
        _lastGenLoadPct[idx]=pct;
        return pct;
      }

      return _lastGenLoadPct[idx];
    }

function pollPedestal(){ try {
/* Electrical gauges */
      var battAmps = getAVar('ELECTRICAL BATTERY LOAD:1, amps');
      var lLoadPct = getGenLoadPct(1);
      var rLoadPct = getGenLoadPct(2);

      var voltMode = getLVar('var_MultimeterMode','Number');
      if(voltMode===undefined||voltMode===null) voltMode=0;
      voltMode=Number(voltMode);
      var modeLabel = VOLT_MODES[voltMode] || 'L GEN';

      var vmEl=document.getElementById('gVoltMode');
      if(vmEl) vmEl.textContent = modeLabel;

      var battAmpsMode = getLVar('var_BatteryAmpsMode','Bool')==1;
      setValDisplay('gBattAmp', battAmpsMode ? fmtNum(battAmps,0) : fmtLoadPctInt(lLoadPct));
      setValDisplay('gRLoad', fmtLoadPctInt(rLoadPct));

      var voltsLVar = VOLT_SOURCE_LVARS[voltMode] || 'var_Multimeter_LeftBusVolts';
      var selVolts = getLVar(voltsLVar,'Number');
      if(selVolts===undefined||selVolts===null){
        // Fallback if multimeter calculation LVars are unavailable.
        if(voltMode===0) selVolts=getAVar('ELECTRICAL MAIN BUS VOLTAGE:@LEFT_BUS, volts');
        else if(voltMode===1) selVolts=getAVar('ELECTRICAL MAIN BUS VOLTAGE:@CENTER_BUS, volts');
        else if(voltMode===2) selVolts=getAVar('ELECTRICAL MAIN BUS VOLTAGE:@RIGHT_BUS, volts');
        else if(voltMode===3) selVolts=getAVar('ELECTRICAL MAIN BUS VOLTAGE:@TRIPLE_FED_BUS, volts');
        else if(voltMode===4) selVolts=(getLVar('bksq_ExternalPowerAvailable','Bool')==1 && getLVar('bksq_ExternalPowerOn','Bool')==1) ? 28.1 : 0;
        else selVolts=getAVar('ELECTRICAL MAIN BUS VOLTAGE:@BATTERY_BUS, volts');
      }
      setValDisplay('gVoltsDC', fmtNum(selVolts,1));

      /* Electrical switches */
      setToggleVisual('battBtn','battInd', getLVar('VAR_BATTERYTIE','Number')==1);

      var genLOn=getAVar('GENERAL ENG MASTER ALTERNATOR:1, Bool')==1;
      var genLRst=getLVar('VAR_GENERATORRESET_L','Bool')==1;
      if(!genLOn) _genLPhase=0;
      setLamps(['genLRstLamp','genLOnLamp','genLOffLamp'], genLRst?0:(genLOn?1:2));

      var genROn=getAVar('GENERAL ENG MASTER ALTERNATOR:2, Bool')==1;
      var genRRst=getLVar('VAR_GENERATORRESET_R','Bool')==1;
      if(!genROn) _genRPhase=0;
      setLamps(['genRRstLamp','genROnLamp','genROffLamp'], genRRst?0:(genROn?1:2));
      setToggleVisual('gpuBtn','gpuInd', getLVar('BKSQ_EXTERNALPOWERON','Bool')==1);
      setToggleVisual('extPwrBtn','extPwrInd', getLVar('var_ExternalPowerSwitch','Bool')==1);
      setToggleVisual('battAmpsBtn','battAmpsInd', getLVar('var_BatteryAmpsMode','Bool')==1);
      var btO=getLVar('var_busTieManOpen','Bool'), btC=getLVar('var_busTieManClose','Bool');
      setLamps(['btCloseLamp','btNormLamp','btOpenLamp'], btC==1?0:btO==1?2:1);

      var stbyOn=getLVar('var_StandbyInstrumentsSwitch','Bool')==1;
      setLamps(['stbyOnLamp','stbyOffLamp'], stbyOn?0:1);
      setToggleVisual('stbyPwrBtn','stbyPwrInd', getLVar('var_StandbyBatteryPushTest','Bool')==1);
      setToggleVisual('avBlowBtn','avBlowInd', getLVar('var_AvionicsAlternateBlowerSwitch','Bool')==1);
      setToggleVisual('gndCommBtn','gndCommInd', getLVar('var_GroundComOn','Bool')==1);

      /* Engine */
      setLamps(['ignLArmLamp','ignLOffLamp'], getLVar('var_AutoIgnitionSwitch_L','Bool')==1 ? 0 : 1);
      setLamps(['ignRArmLamp','ignROffLamp'], getLVar('var_AutoIgnitionSwitch_R','Bool')==1 ? 0 : 1);
      var af=getLVar('var_AutoFeatherSwitch','Number');
      setLamps(['afTestLamp','afArmLamp','afOffLamp'], af==0?0:af==2?2:1);
      setToggleVisual('propSyncBtn','propSyncInd', getAVar('PROP SYNC ACTIVE, bool')==1);
      var gov=getLVar('var_PropGovTestSwitch_Override','Number');
      setLamps(['govGovLamp','govNormLamp','govLowLamp'], gov==0?0:gov==2?2:1);
      var stL=getLVar('var_StarterSwitch_L','Number');
      setLamps(['stLOnLamp','stLOffLamp','stLSOLamp'], stL==0?0:stL==2?2:1);
      var stR=getLVar('var_StarterSwitch_R','Number');
      setLamps(['stROnLamp','stROffLamp','stRSOLamp'], stR==0?0:stR==2?2:1);

      /* Fuel gauges */
      var fuelConv = getLVar('AAOFuelConv','Number');
      var isKg = (fuelConv==1);
      var unitLabel = isKg ? 'KG' : 'LBS';
      var galToLbs=6.7;
      var totalLGal=getAVar('FUEL LEFT QUANTITY, gallons');
      var totalRGal=getAVar('FUEL RIGHT QUANTITY, gallons');
      var auxLGal=getAVar('FUEL TANK LEFT AUX QUANTITY, gallons');
      var auxRGal=getAVar('FUEL TANK RIGHT AUX QUANTITY, gallons');
      var aftL = getLVar('var_AftTankQuantityButton_L','Bool')==1 || getLVar('VAR_AFTTANKQUANTITYBUTTON_L','Bool')==1;
      var aftR = getLVar('var_AftTankQuantityButton_R','Bool')==1 || getLVar('VAR_AFTTANKQUANTITYBUTTON_R','Bool')==1;
      var fuelLGal = aftL ? auxLGal : totalLGal;
      var fuelRGal = aftR ? auxRGal : totalRGal;
      var fuelL = (fuelLGal!==undefined&&fuelLGal!==null) ? Number(fuelLGal)*galToLbs : getLVar('AAOFuelL','Number');
      var fuelR = (fuelRGal!==undefined&&fuelRGal!==null) ? Number(fuelRGal)*galToLbs : getLVar('AAOFuelR','Number');
      if(isKg){
        if(fuelL!==undefined&&fuelL!==null) fuelL = Number(fuelL)*0.45359237;
        if(fuelR!==undefined&&fuelR!==null) fuelR = Number(fuelR)*0.45359237;
      }
      setValDisplay('gFuelL', fmtNum(fuelL,0));
      setValDisplay('gFuelR', fmtNum(fuelR,0));
      var uL=document.getElementById('gFuelLUnit');
      var uR=document.getElementById('gFuelRUnit');
      if(uL) uL.textContent=unitLabel;
      if(uR) uR.textContent=unitLabel;

      var fTemp = getLVar('var_FuelTemperature','Number');
      if(fTemp!==undefined&&fTemp!==null) fTemp = Number(fTemp) - 273.15;
      if(fTemp===undefined||fTemp===null) fTemp=getAVar('ENG OIL TEMPERATURE:1, celsius');
      if(fTemp===undefined||fTemp===null) fTemp=getAVar('AMBIENT TEMPERATURE, celsius');
      setValDisplay('gFuelTemp', fmtNum(fTemp,0));

      /* Fuel switches */
      setToggleVisual('fuelPumpLBtn','fuelPumpLInd', getLVar('var_StandbyFuelPump_L','Number')==1);
      setToggleVisual('fuelPumpRBtn','fuelPumpRInd', getLVar('var_StandbyFuelPump_R','Number')==1);
      setToggleVisual('aftTankLBtn','aftTankLInd', aftL);
      setToggleVisual('aftTankRBtn','aftTankRInd', aftR);
      var xf=getLVar('var_FuelTransferKnob','Number');
      setLamps(['xferRtoLLamp','xferOffLamp','xferLtoRLamp'], xf==0?0:xf==2?2:1);

      /* Lower pedestal — trim + brake */
      var pt=getLVar('var_PitchTrimModeSwitch','Number');
      setLamps(['ptNormLamp','ptOffLamp','ptStbyLamp'], pt==0?0:pt==2?2:1);
      setToggleVisual('rtmBtn','rtmInd', getLVar('var_RollTrimModeSwitch','Bool')==1);
      setToggleVisual('rudTmBtn','rudTmInd', getLVar('var_RudderTrimModeSwitch','Bool')==1);
      setToggleVisual('prkBrkBtn','prkBrkInd', getAVar('BRAKE PARKING POSITION, bool')==1);
} catch(e){} }

/* AVNCS transponder lamps + ident */

function getXpdrState(){ try { return webApi.GetSimVar('(A:TRANSPONDER STATE:1, Enum)'); } catch(e){ return 0; } }
function getXpdrIdent(){ try { return webApi.GetSimVar('(A:TRANSPONDER IDENT:1, Bool)'); } catch(e){ return 0; } }
function setXpdrModeVisual(st){
  var altL=document.getElementById('xpdrAltLamp');
  var stbyL=document.getElementById('xpdrStbyLamp');
  if(!altL||!stbyL) return;
  altL.classList.toggle('on', st===4);
  stbyL.classList.toggle('on', st===1);
}
var _xpdrIdentVal = 0, _xpdrLastPoll = 0;
function updateXpdrVisuals(){
  var st = getXpdrState();
  var on = (st !== 0);
  setToggleVisual('xpdrPwrToggle','xpdrPwrInd', on);
  setXpdrModeVisual(st);
  var now = Date.now();
  if (now - _xpdrLastPoll > 300) { _xpdrIdentVal = getXpdrIdent(); _xpdrLastPoll = now; }
  setToggleVisual('xpdrIdentBtn','xpdrIdentInd', _xpdrIdentVal==1);
}
function toggleXpdrPwr(){ try { sendP('SSP_AVNCS_XPDR_PWR_TOGGLE'); setTimeout(updateXpdrVisuals, 120); } catch(e){} }
function toggleXpdrMode(){ try { sendP('SSP_AVNCS_XPDR_MODE_TOGGLE'); setTimeout(updateXpdrVisuals, 120); } catch(e){} }
function xpdrIdent(){ try { sendP('SSP_AVNCS_XPDR_IDENT_PRESS'); setTimeout(function(){ _xpdrLastPoll=0; updateXpdrVisuals(); }, 120); } catch(e){} }

function pollAvncsXpdr(){ try { updateXpdrVisuals(); } catch(e){} }

window.SSP_PANEL_OVERRIDES = window.SSP_PANEL_OVERRIDES || {};
window.SSP_PANEL_OVERRIDES.onPoll = function(panelId, ctx){
  if (panelId === 'ecs') pollEcs();
  else if (panelId === 'pedestal') pollPedestal();
  else if (panelId === 'autopilot') pollAvncsXpdr();
};
window.SSP_PANEL_OVERRIDES.polls = window.SSP_PANEL_OVERRIDES.polls || {};
/* COM spacing: interior uses (A:COM SPACING MODE:n, enum) 0 != for non-default; lamp = both radios in 8.33 / non-zero spacing */
window.SSP_PANEL_OVERRIDES.polls.rtu833Both = function () {
  try {
    var m1 = Number(getAVar('COM SPACING MODE:1, Enum'));
    var m2 = Number(getAVar('COM SPACING MODE:2, Enum'));
    if (!isFinite(m1) || !isFinite(m2)) return;
    var on = m1 !== 0 && m2 !== 0;
    setToggleVisual('rtu833Btn', 'rtu833Ind', on);
  } catch (e) {}
};
